const citiesWithProvinces = [
  { city: "Markham", province: "Ontario" },
  { city: "Timmins", province: "Ontario" },
  { city: "Toronto", province: "Ontario" },
  { city: "Vaughan", province: "Ontario" },
  { city: "Waterloo", province: "Ontario" },
  { city: "Welland", province: "Ontario" },
  { city: "Windsor", province: "Ontario" },
  { city: "Woodstock", province: "Ontario" },
  // Add more cities here
  { city: "Ajax", province: "Ontario" },
  { city: "Whitby", province: "Ontario" },
  { city: "Courtice", province: "Ontario" },
  { city: "Bowmanville", province: "Ontario" },
  { city: "Innisfil", province: "Ontario" },
  { city: "Bradford", province: "Ontario" },
  { city: "Calgary", province: "Ontario" },
  { city: "Richmond Hill", province: "Ontario" },
  { city: "Aurora", province: "Ontario" },
  { city: "Newmarket", province: "Ontario" },
  { city: "Barrie", province: "Ontario" },
  { city: "East Gwillimbury", province: "Ontario" },
];
export const allCities = [
  { city: "Barrie", province: "Ontario" },
  { city: "Belleville", province: "Ontario" },
  { city: "Brampton", province: "Ontario" },
  { city: "Brant", province: "Ontario" },
  { city: "Brantford", province: "Ontario" },
  { city: "Brockville", province: "Ontario" },
  { city: "Burlington", province: "Ontario" },
  { city: "Cambridge", province: "Ontario" },
  { city: "Clarence-Rockland", province: "Ontario" },
  { city: "Cornwall", province: "Ontario" },
  { city: "Dryden", province: "Ontario" },
  { city: "Elliot Lake", province: "Ontario" },
  { city: "Greater Sudbury", province: "Ontario" },
  { city: "Guelph", province: "Ontario" },
  { city: "Haldimand County", province: "Ontario" },
  { city: "Hamilton", province: "Ontario" },
  { city: "Kawartha Lakes", province: "Ontario" },
  { city: "Kenora", province: "Ontario" },
  { city: "Kingston", province: "Ontario" },
  { city: "Kitchener", province: "Ontario" },
  { city: "London", province: "Ontario" },
  { city: "Markham", province: "Ontario" },
  { city: "Mississauga", province: "Ontario" },
  { city: "Niagara Falls", province: "Ontario" },
  { city: "Norfolk County", province: "Ontario" },
  { city: "North Bay", province: "Ontario" },
  { city: "Orillia", province: "Ontario" },
  { city: "Oshawa", province: "Ontario" },
  { city: "Ottawa", province: "Ontario" },
  { city: "Owen Sound", province: "Ontario" },
  { city: "Pembroke", province: "Ontario" },
  { city: "Peterborough", province: "Ontario" },
  { city: "Pickering", province: "Ontario" },
  { city: "Port Colborne", province: "Ontario" },
  { city: "Prince Edward County", province: "Ontario" },
  { city: "Quinte West", province: "Ontario" },
  { city: "Richmond Hill", province: "Ontario" },
  { city: "Sarnia", province: "Ontario" },
  { city: "Sault Ste Marie", province: "Ontario" },
  { city: "St Catharines", province: "Ontario" },
  { city: "St Thomas", province: "Ontario" },
  { city: "Stratford", province: "Ontario" },
  { city: "Temiskaming Shores", province: "Ontario" },
  { city: "Thorold", province: "Ontario" },
  { city: "Thunder Bay", province: "Ontario" },
  { city: "Markham", province: "Ontario" },
  { city: "Timmins", province: "Ontario" },
  { city: "Toronto", province: "Ontario" },
  { city: "Vaughan", province: "Ontario" },
  { city: "Waterloo", province: "Ontario" },
  { city: "Welland", province: "Ontario" },
  { city: "Windsor", province: "Ontario" },
  { city: "Woodstock", province: "Ontario" },
  // Add more cities here
  { city: "Ajax", province: "Ontario" },
  { city: "Whitby", province: "Ontario" },
  { city: "Courtice", province: "Ontario" },
  { city: "Bowmanville", province: "Ontario" },
  { city: "Innisfil", province: "Ontario" },
  { city: "Bradford", province: "Ontario" },
  { city: "Calgary", province: "Ontario" },
  { city: "Richmond Hill", province: "Ontario" },
  { city: "Aurora", province: "Ontario" },
  { city: "Newmarket", province: "Ontario" },
  { city: "Barrie", province: "Ontario" },
  { city: "East Gwillimbury", province: "Ontario" },
];

export default citiesWithProvinces;
